name: aaltosulku
baseurl: /aaltosulku
permalink: none
pygments: true
prose:
  rooturl: '_posts'
  siteurl: 'http://OHKEY-dev.github.io/aaltosulku'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
      - name: "category"
        field:
          element: "text"
          label: "Kategoria"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "subject"
        field:
          element: "multiselect"
          label: "Aihealue"
          options:
            - name: "Ohje"
              value: "guide"
            - name: "Snippet"
              value: "snippet"
