name: aaltosulku
baseurl: /aaltosulku
permalink: none
highlighter: true
prose:
  rooturl: '_posts'
  siteurl: 'http://OHKEY-dev.github.io/aaltosulku'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Julkaistu"
          value: true
      - name: "category"
        field:
          element: "select"
          label: "Kategoria"
          options:
            - name: "Git"
              value: "git"
            - name: "Eclipse"
              value: "eclipse"
            - name: "Jekyll"
              value: "jekyll"
            - name: "Sublime Text"
              value: "sublime text"
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""