name: aaltosulku
baseurl: /aaltosulku
permalink: none
pygments: true
prose:
  rooturl: '_posts'
  siteurl: 'http://OHKEY-dev.github.io/aaltosulku'
  metadata:
    _posts:
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: true
